package real;

import com.ntt.tc.data.C8yData;

/**
 * HandshakeResponse class
 * This source is machine-generated from c8y-markdown docs.
 */
public class HandshakeResponse extends C8yData {
	/**
	 * Id of message passed in request message
	 * <pre>
	 * Occurs : 1
	 * </pre>
	 */
	public int id;
	
	/**
	 * Name of channel, required value "/meta/handshake".
	 * <pre>
	 * Occurs : 1
	 * </pre>
	 */
	public String channel;
	
	/**
	 * Bayeux protocol version used by server.
	 * <pre>
	 * Occurs : 0..1
	 * </pre>
	 */
	public String version;
	
	/**
	 * Minimum client-side Bayeux protocol version required by server.
	 * <pre>
	 * Occurs : 0..1
	 * </pre>
	 */
	public String minimumVersion;
	
	/**
	 * Connection types supported by both client and server (i.e., intersection
	 * between client and server options).
	 * <pre>
	 * Occurs : 0..1
	 * </pre>
	 */
	public String[] supportedConnectionTypes;
	
	/**
	 * Unique client ID generated by server.
	 * <pre>
	 * Occurs : 0..1
	 * </pre>
	 */
	public String clientId;
	
	/**
	 * Result of handshake.
	 * <pre>
	 * Occurs : 1
	 * </pre>
	 */
	public boolean successful;
	
	/**
	 * Handshake failure reason.
	 * <pre>
	 * Occurs : 0..1
	 * </pre>
	 */
	public String error;
	
}
